import { startAuthentication, startRegistration } from '@simplewebauthn/browser'
import { supabase } from './supabase'

const KEY='familia-noa-member', PROFILE_KEY='familia-noa-profile', PASSKEY_KEY='familia-noa-passkey-member'
const supported=()=>typeof window!=='undefined'&&!!window.PublicKeyCredential&&window.isSecureContext
async function call(action:string,payload:Record<string,unknown>={}){const {data,error}=await supabase.functions.invoke('family-passkeys-v2',{body:{action,...payload}});if(error)throw new Error(error.message||'No se pudo completar la operación.');if(data?.error)throw new Error(data.error);return data}
function session(p:{id:string,name:string}){localStorage.setItem(KEY,p.name);sessionStorage.setItem(PROFILE_KEY,JSON.stringify(p));location.reload()}
async function biometric(button:HTMLButtonElement,error:HTMLElement){button.disabled=true;error.textContent='Verificando…';try{const {token,options}=await call('auth-options');const response=await startAuthentication({optionsJSON:options});const r=await call('auth-verify',{token,response});session(r.profile)}catch(e){if((e as Error).name!=='NotAllowedError'&&(e as Error).name!=='AbortError')error.textContent=e instanceof Error?e.message:'No se pudo entrar.';button.disabled=false}}
function addLogin(){if(!supported()||localStorage.getItem(PASSKEY_KEY)!=='enabled')return;const members=document.querySelector('.members');if(!members||document.querySelector('#biometricLogin'))return;const w=document.createElement('div');w.className='biometric-access';w.innerHTML='<button id="biometricLogin" class="primary biometric-button" type="button">🔐 Entrar con huella / Face ID</button><div id="biometricError" aria-live="polite"></div><div class="biometric-divider"><span>o entra con tu perfil</span></div>';members.before(w);const b=w.querySelector<HTMLButtonElement>('#biometricLogin')!,e=w.querySelector<HTMLElement>('#biometricError')!;b.onclick=()=>biometric(b,e)}
async function register(memberId:string,house:string,nickname:string){try{const {token,options}=await call('register-options',{member_id:memberId,house_number:house,nickname});const response=await startRegistration({optionsJSON:options});await call('register-verify',{token,response});localStorage.setItem(PASSKEY_KEY,'enabled');localStorage.setItem('familia-noa-passkey-member-id',memberId);alert('Listo. Este teléfono ya puede entrar con huella o reconocimiento facial.');location.reload()}catch(e){if((e as Error).name!=='NotAllowedError'&&(e as Error).name!=='AbortError')alert(e instanceof Error?e.message:'No se pudo activar la biometría.')}}
function addSetup(){if(!supported()||localStorage.getItem(PASSKEY_KEY)==='enabled')return;const home=document.querySelector('.shell'),change=document.querySelector('#change');if(!home||!change||document.querySelector('#enableBiometric'))return;const b=document.createElement('button');b.id='enableBiometric';b.className='biometric-setup';b.textContent='🔐 Activar huella / Face ID';change.parentElement?.after(b);b.onclick=async()=>{const raw=sessionStorage.getItem(PROFILE_KEY);if(!raw)return;const p=JSON.parse(raw) as {id:string,name:string};const house=prompt('Confirma el número de la casa.');if(!house)return;const nickname=prompt(`Confirma tu apodo familiar, ${p.name}.`);if(nickname)await register(p.id,house,nickname)}}
const observer=new MutationObserver(()=>{addLogin();addSetup()});observer.observe(document.body,{childList:true,subtree:true});addLogin();addSetup()
