import { supabase } from './supabase'

const BUCKET='family-photos'
const PROFILE_KEY='familia-noa-profile'
const css=`
.profile-cover-editor{margin:0 0 18px}.profile-cover-preview{height:118px;border-radius:20px;background:linear-gradient(135deg,rgba(0,0,0,.08),rgba(0,0,0,.02));background-size:cover;background-position:center;display:flex;align-items:flex-end;justify-content:flex-end;padding:10px;box-sizing:border-box}.profile-cover-button{border:0;border-radius:999px;padding:9px 13px;background:rgba(0,0,0,.72);color:#fff;font:600 12px system-ui;cursor:pointer}.profile-cover-label{display:block;font-size:12px;text-transform:uppercase;letter-spacing:.12em;margin:0 0 8px;opacity:.65}.profile-detail-cover{width:100%;height:150px;border-radius:22px;object-fit:cover;margin-bottom:-42px;position:relative;z-index:0}.profile-detail .profile-head{position:relative;z-index:1}
`
function inject(){if(document.querySelector('#profile-cover-css'))return;const s=document.createElement('style');s.id='profile-cover-css';s.textContent=css;document.head.appendChild(s)}
function current(){const raw=sessionStorage.getItem(PROFILE_KEY);return raw?JSON.parse(raw):null}
function url(path:string|null){return path?supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl:''}
async function addCoverEditor(menu:Element){if(menu.querySelector('.profile-cover-editor'))return;const p=current();if(!p)return;const {data}=await supabase.from('family_profiles').select('cover_path').eq('member_id',p.id).maybeSingle();const path=data?.cover_path||'';const wrap=document.createElement('div');wrap.className='profile-cover-editor';wrap.innerHTML=`<label class="profile-cover-label">Portada de mi perfil</label><div class="profile-cover-preview" style="${path?`background-image:url('${url(path)}')`:''}"><button type="button" class="profile-cover-button">${path?'Cambiar portada':'Añadir portada'}</button></div><input type="file" accept="image/*" style="display:none">`;const field=menu.querySelector('.profile-field');field?.before(wrap);const input=wrap.querySelector<HTMLInputElement>('input')!;wrap.querySelector('button')!.addEventListener('click',()=>input.click());input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){alert('Selecciona una imagen.');return}if(file.size>10*1024*1024){alert('La portada debe pesar menos de 10 MB.');return}const button=wrap.querySelector<HTMLButtonElement>('button')!;button.disabled=true;button.textContent='Subiendo…';try{const newPath=`profile-covers/${p.id}-${Date.now()}.jpg`;const {error}=await supabase.storage.from(BUCKET).upload(newPath,file,{contentType:file.type,upsert:false});if(error)throw error;const {error:dbError}=await supabase.from('family_profiles').upsert({member_id:p.id,cover_path:newPath,updated_at:new Date().toISOString()});if(dbError)throw dbError;wrap.querySelector<HTMLElement>('.profile-cover-preview')!.style.backgroundImage=`url('${url(newPath)}')`;button.textContent='Portada actualizada ✓';setTimeout(()=>button.textContent='Cambiar portada',1800)}catch(err){button.textContent=err instanceof Error?err.message:'No se pudo subir';setTimeout(()=>button.textContent=path?'Cambiar portada':'Añadir portada',2200)}finally{button.disabled=false}})}
async function decorateDetail(detail:Element){if(detail.querySelector('.profile-detail-cover'))return;const title=detail.querySelector('.profile-detail-head');const name=(title?.querySelector('b')?.textContent||'').trim();if(!name)return;const {data:member}=await supabase.from('family_members').select('id').eq('name',name).maybeSingle();if(!member)return;const {data}=await supabase.from('family_profiles').select('cover_path').eq('member_id',member.id).maybeSingle();if(!data?.cover_path)return;const img=document.createElement('img');img.className='profile-detail-cover';img.src=url(data.cover_path);img.alt='';title?.after(img)}
function observe(){inject();const obs=new MutationObserver(()=>{document.querySelectorAll('.profile-menu').forEach(m=>addCoverEditor(m));document.querySelectorAll('.profile-detail').forEach(d=>decorateDetail(d))});obs.observe(document.body,{childList:true,subtree:true});document.querySelectorAll('.profile-menu').forEach(m=>addCoverEditor(m));document.querySelectorAll('.profile-detail').forEach(d=>decorateDetail(d))}
observe()
